services:
  - mysql:latest

variables:
  # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
  MYSQL_DATABASE: test
  MYSQL_ROOT_PASSWORD:

before_script:
# Install dependencies
- bash ci/docker_install.sh > /dev/null
- cp gitlab.conf /etc/apache2/sites-available
- service apache2 start
- a2ensite gitlab
- a2enmod rewrite
- service apache2 restart
- pwd
- composer install
- mkdir var/jwt
- openssl genrsa -out var/jwt/private.pem -aes256 -passout pass:secret 4096
- openssl rsa -pubout -in var/jwt/private.pem -out var/jwt/public.pem -passin pass:secret
- bin/console doctrine:database:create --env=test
- bin/console doctrine:schema:update --force --env=test
- sudo chmod 777 var -R
- sudo chown www-data.www-data var/jwt/*.*

# We test PHP5.6
test:5.6:
  image: php:5.6.30-apache
  script:
  - phpunit

# We test PHP7.0 (good luck with that)
test:7.0:
  image: php:7.1.6-apache
  script:
  - phpunit