build:
  tests:
    before:
      - mkdir var/jwt
      - openssl genrsa -out var/jwt/private.pem -aes256 -passout pass:secret 4096
      - openssl rsa -pubout -in var/jwt/private.pem -out var/jwt/public.pem -passin pass:secret
      - bin/console doctrine:database:create --env=test
      - bin/console doctrine:schema:update --force --env=test
      - sudo chmod 777 var -R
      - sudo chown www-data.www-data var/jwt/*.*
      - mv behat.scrutinizer.yml behat.yml
      - mv phpunit.scrutinizer.xml phpunit.xml
    override:
      -
        command: 'vendor/bin/phpunit'
        coverage:
          file: 'coverage.clover'
          format: 'clover'
      - command: 'vendor/bin/behat'
      - command: 'php-scrutinizer-run'
  environment:
    php:
      version: 7.1