app.swagger_ui:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /doc

api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation
    defaults:
      _format: json

defaultCatchAll:
    path:     /{path}
    defaults:
        _controller: AppBundle:Api\ApiVersion:handleVersion
        path: /
        permanent: true
    requirements:
        path: ".+"
