app:
    resource: "@AppBundle/Controller/Web"
    type:     annotation

app.swagger_ui:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc

api:
    resource: "@AppBundle/Controller/Api"
    type:     annotation
    defaults:
      _format: json

defaultCatchAll:
    path:     /api/{path}
    defaults:
        _controller: AppBundle:Api\ApiVersion:handleVersion
        path: /
        permanent: true
    requirements:
        path: ".+"

homepage:
  path: /
  defaults:
    _controller: AppBundle:Web/Main:homepage