# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
  encoders:
    AppBundle\Entity\User: bcrypt
  # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
  providers:
    our_users:
      entity: {class: AppBundle\Entity\User, property: userName}
  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    api:
      pattern: ^/api/
      anonymous: ~
      guard:
        authenticators:
          - app.security.jwt_token_authenticator
    main:
      anonymous: ~
      guard:
        authenticators:
          - app.security.login_form_authenticator
      logout:
        path: /logout
  access_control:
  role_hierarchy:
    ROLE_ADMIN: [ROLE_MANAGER, ROLE_TEST]
    #- { path: ^/admin, roles: ROLE_ADMIN}
