# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
  app.security.login_form_authenticator:
    class: AppBundle\Security\LoginFormAuthenticator
    arguments: ["@form.factory", "@doctrine.orm.entity_manager","@router", "@security.password_encoder"]

  app.security.jwt_token_authenticator:
    class: AppBundle\Security\JwtTokenAuthenticator
    arguments: ["@lexik_jwt_authentication.encoder", "@doctrine.orm.entity_manager", "@api.response_factory"]

  app.doctrine.hash_password_listener:
    class: AppBundle\Doctrine\HashPasswordListener
    arguments: ["@security.password_encoder"]
    tags:
      - {name: doctrine.event_subscriber}

  api_exception_subscriber:
    class: AppBundle\EventListener\ApiExceptionSubscriber
    arguments: ['%kernel.debug%' , '@logger', '@api.response_factory']
    tags:
      - { name: kernel.event_subscriber }

  api.response_factory:
    class: AppBundle\Api\ResponseFactory

  pagination_factory:
    class: AppBundle\Pagination\PaginationFactory
    arguments: ["@router"]

  link_serialization_subscriber:
    class: AppBundle\Serializer\LinkSerializationSubscriber
    arguments: ["@router", "@annotation_reader"]
    tags:
      - { name: jms_serializer.event_subscriber }

  custom_hateoas_json_serializer:
    class: AppBundle\Serializer\CustomHATEOASJsonSerializer