# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
  app_user.twofactor.email.provider.class: AppBundle\Security\TwoFactor\Email\Helper
  app_user.twofactor.email.interactive_login_listener.class: AppBundle\Security\TwoFactor\Email\InteractiveLoginListener
  app_user.twofactor.email.request_listener.class: AppBundle\Security\TwoFactor\Email\RequestListener

  app.security.param.servername: "TestServer"
  app_user.twofactor.google.class: Google\Authenticator\GoogleAuthenticator
  app_user.twofactor.google.provider.class: AppBundle\Security\TwoFactor\Google\Helper
  app_user.twofactor.google.interactive_login_listener.class: AppBundle\Security\TwoFactor\Google\InteractiveLoginListener
  app_user.twofactor.google.request_listener.class: AppBundle\Security\TwoFactor\Google\RequestListener

services:
  app.security.twofactor.google:
    class: "%app_user.twofactor.google.class%"
  app.security.twofactor.google.provider:
    class: "%app_user.twofactor.google.provider.class%"
    arguments: ["%app.security.param.servername%", "@app.security.twofactor.google"]
  app.security.twofactor.google.interactive_login_listener:
    class: "%app_user.twofactor.google.interactive_login_listener.class%"
    arguments: ["@app.security.twofactor.google.provider"]
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }
  app.security.twofactor.google.request_listener:
    class: "%app_user.twofactor.google.request_listener.class%"
    arguments: ["@app.security.twofactor.google.provider","@security.token_storage", "@templating","@router"]
    tags:
      - { name: kernel.event_listener, event: kernel.request, method: onCoreRequest, priority: -1 }

  app.security.twofactor.email.provider:
    class: "%app_user.twofactor.email.provider.class%"
    arguments: ["@doctrine.orm.entity_manager", "@swiftmailer.mailer"]

  app.security.twofactor.email.interactive_login_listener:
    class: "%app_user.twofactor.email.interactive_login_listener.class%"
    arguments: ["@app.security.twofactor.email.provider"]
#    tags:
#      - { name: kernel.event_listener, event: security.interactive_login, method: onSecurityInteractiveLogin }

  app.security.twofactor.email.request_listener:
    class: "%app_user.twofactor.email.request_listener.class%"
    arguments: ["@app.security.twofactor.email.provider", "@security.token_storage", "@templating", "@router"]
#    tags:
#      - { name: kernel.event_listener, event: kernel.request, method: onCoreRequest, priority: -1 }

  app.security.login_form_authenticator:
    class: AppBundle\Security\LoginFormAuthenticator
    arguments: ["@form.factory", "@doctrine.orm.entity_manager","@router", "@security.password_encoder"]

  app.security.jwt_token_authenticator:
    class: AppBundle\Security\JwtTokenAuthenticator
    arguments: ["@lexik_jwt_authentication.encoder", "@doctrine.orm.entity_manager", "@api.response_factory"]

  app.doctrine.hash_password_listener:
    class: AppBundle\Doctrine\HashPasswordListener
    arguments: ["@security.password_encoder"]
    tags:
      - {name: doctrine.event_subscriber}

  api_exception_subscriber:
    class: AppBundle\EventListener\ApiExceptionSubscriber
    arguments: ['%kernel.debug%' , '@logger', '@api.response_factory']
    tags:
      - { name: kernel.event_subscriber }

  api.response_factory:
    class: AppBundle\Api\ResponseFactory

  pagination_factory:
    class: AppBundle\Pagination\PaginationFactory
    arguments: ["@router"]

  link_serialization_subscriber:
    class: AppBundle\Serializer\LinkSerializationSubscriber
    arguments: ["@router", "@annotation_reader"]
    tags:
      - { name: jms_serializer.event_subscriber }

  custom_hateoas_json_serializer:
    class: AppBundle\Serializer\CustomHATEOASJsonSerializer