version: '2'
services:
  #apache/php
  hn_api:
    build: ./hn_api
    image: hn_api
    depends_on:
      - "hn_db"
    hostname: "sf3"
    container_name: "hn_api"
    ports:
      - 8080:80   #apache
    volumes:
      - "../:/var/www/html"
      - "~/.composer:/var/www/.composer"
      - ./hn_api/zshrc.dist:/var/www/.zshrc:ro
      - ./data/apache/logs:/var/log/apache2
    links:
      - hn_db
    env_file:
      - docker-env

  #mysql
  hn_db:
    image: mysql:latest
    container_name: "hn_db"
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./data/sql:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/z_my.cnf

  #phpmyadmin
  hn_pma:
    image: phpmyadmin/phpmyadmin
    container_name: "hn_pma"
    links:
      - hn_db
    depends_on:
      - "hn_db"
    ports:
      - 8081:80
#        restart: always
    environment:
      - PMA_ARBITRARY=1
      - PMA_PORT=3306
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
