services:
  AppBundle\EventListener\ApiExceptionSubscriber:
    arguments: ['%kernel.debug%' , '@logger', '@AppBundle\Api\ResponseFactory']
    tags:
      - { name: kernel.event_subscriber }

  AppBundle\Api\ResponseFactory:

  AppBundle\Pagination\PaginationFactory:
    arguments: ["@router"]

  AppBundle\Serializer\LinkSerializationSubscriber:
    arguments: ["@router", "@annotation_reader"]
    tags:
      - { name: jms_serializer.event_subscriber }

  AppBundle\Serializer\CustomHATEOASJsonSerializer: