parameters:
  app.security.param.servername: "TestServer"

services:
  AppBundle\Security\LoginFormAuthenticator:
    arguments: ["@form.factory", "@app.user_repository","@router", "@security.password_encoder"]

  AppBundle\Security\JwtTokenAuthenticator:
    arguments: ["@lexik_jwt_authentication.encoder", "@app.user_repository", '@AppBundle\Api\ResponseFactory']

  AppBundle\Doctrine\HashPasswordListener:
    arguments: ["@security.password_encoder"]
    tags:
      - {name: doctrine.event_subscriber}

  AppBundle\Security\Encryption\EncryptionService:
      arguments: ["%defuse_key%","@logger"]
