services:
  app.security.encryption_service:
    class: AppBundle\Security\Encryption\EncryptionService
    arguments: ["%defuse_key%","@logger"]

  app.security.login_form_authenticator:
    class: AppBundle\Security\LoginFormAuthenticator
    arguments: ["@form.factory", "@doctrine.orm.entity_manager","@router", "@security.password_encoder"]

  app.security.jwt_token_authenticator:
    class: AppBundle\Security\JwtTokenAuthenticator
    arguments: ["@lexik_jwt_authentication.encoder", "@doctrine.orm.entity_manager", "@api.response_factory"]

  app.doctrine.hash_password_listener:
    class: AppBundle\Doctrine\HashPasswordListener
    arguments: ["@security.password_encoder"]
    tags:
      - {name: doctrine.event_subscriber}